### ISSUE TITLE
Cumulocity `/cep/realtime` endpoint is deprecated

### ISSUE THREAD

**Issue by sagscmi** [io-key/node-red-contrib-io-key#29]
Hi @PatersonKopp,

Firstly, many thanks on behalf the Cumulocity community for your efforts in developing and maintaining this project.  I represent the Cumulocity R&D team, and I wanted to make sure you were aware that the `/cep/realtime` endpoint that you use to receive notifications from Cumulocity has been deprecated since the 10.9 release of the platform: https://cumulocity.com/releasenotes/release-10-9-0/announcements-10-9-0/.  It is replaced by the `/notification/realtime` endpoint.

We have no concrete plan at this time to remove the `/cep/realtime` endpoint from Cumulocity, but we reserve the right to schedule such removal at any time.  Therefore our strong recommendation to all users of this endpoint is to migrate to `/notification/realtime` as soon as reasonably possible.

Many thanks and best regards,

Scott Mitchell
Software AG / Cumulocity IoT R&D

**Comment by PatersonKopp** [comment]
Hey @sagscmi, thanks for the information! We already have added support for the websocket based notification2 API and recommend to the user to use this instead. The /cep endpoint is only there to not break anything. In case it is removed fully, we'll also remove it.
